
CREATE DATABASE IF NOT EXISTS Musica;
USE Musica;

CREATE TABLE IF NOT EXISTS GENERO (
 NOME VARCHAR(100) NOT NULL PRIMARY KEY,
 ICONE VARCHAR(100),
 COR VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS Musica (
 CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 CANTOR VARCHAR(50),
 NOME VARCHAR(50),
 DURACAO TIME,
 URL_IMAGEM VARCHAR(255),
 NOME_GENERO VARCHAR(30),
 CONSTRAINT FK_MUSICA_GENERO FOREIGN KEY (NOME_GENERO) REFERENCES GENERO (NOME)
);

CREATE TABLE IF NOT EXISTS LOGIN (
 USUARIO VARCHAR(100) PRIMARY KEY,
 SENHA VARCHAR(100) NOT NULL 
);

ALTER TABLE Musica
ADD ativos bool default 0;